### ISSUE TITLE
Query about the Figure 1 in paper

### ISSUE THREAD

**Issue by tangqideng** [huankoh/CST-GL#3]
Hi! Can you please specify the source of dimensions B1 and B2 in the Figure .1 SMD dataset, particularly which machine they originate from? This information is crucial for our analysis. Thank you!
![image](https://github.com/huankoh/CST-GL/assets/108042679/b4e12393-8086-4a3e-8a38-8668a956fe05)

**Comment by huankoh** [comment]
Thanks for the comment. I can't remember which SMD machine / channels , I remember that I scanned through all possible machine dataset to find one that is most intuitive to explain in the introduction.

Also, please note that to make the examples stronger in the introduction, I have modified some of the dataset to deliver the message. Hence, in the introduction, we mentioned that this is a "real-world inspired example" rather than "real-world example"
